# 1.3. Introducing the multidimensional array in NumPy for fast array computations

In [1]:
import random
import numpy as np

In [2]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [3]:
x[:3], y[:3]

([0.6710408482710831, 0.9388309197532998, 0.08232946166835087],
 [0.7455319933539708, 0.1388748637868008, 0.8680096369048309])

In [4]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[1.416572841625054, 1.0777057835401007, 0.9503390985731818]

In [5]:
%timeit [x[i] + y[i] for i in range(n)]

116 ms ± 609 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
xa = np.array(x)
ya = np.array(y)

In [7]:
xa[:3]

array([0.67104085, 0.93883092, 0.08232946])

In [8]:
za = xa + ya
za[:3]

array([1.41657284, 1.07770578, 0.9503391 ])

In [9]:
%timeit xa + ya

1.62 ms ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%timeit sum(x)  # pure Python

3.21 ms ± 37.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit np.sum(xa)  # NumPy

322 µs ± 3.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
d = [abs(x[i] - y[j])
     for i in range(1000)
     for j in range(1000)]

In [13]:
d[:3]

[0.07449114508288768, 0.5321659844842823, 0.19696878863374778]

In [14]:
da = np.abs(xa[:1000, np.newaxis] - ya[:1000])

In [15]:
da

array([[0.07449115, 0.53216598, 0.19696879, ..., 0.10356822, 0.66160885,
        0.05968582],
       [0.19329893, 0.79995606, 0.07082128, ..., 0.37135829, 0.92939892,
        0.32747589],
       [0.66320253, 0.0565454 , 0.78568018, ..., 0.48514316, 0.07289746,
        0.52902556],
       ...,
       [0.14101273, 0.74766986, 0.01853509, ..., 0.3190721 , 0.87711273,
        0.2751897 ],
       [0.17906014, 0.42759699, 0.30153778, ..., 0.00100077, 0.55703985,
        0.04488317],
       [0.15868182, 0.76533895, 0.03620417, ..., 0.33674118, 0.89478181,
        0.29285878]])

In [16]:
%timeit [abs(x[i] - y[j]) \
         for i in range(1000) \
         for j in range(1000)]

143 ms ± 2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%timeit np.abs(xa[:1000, np.newaxis] - ya[:1000])

3.18 ms ± 26.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
